version: "3"
services:
    mongodb:
        environment:
            - MONGO_INITDB_ROOT_USERNAME=max
            - MONGO_INITDB_ROOT_PASSWORD=secret
        volumes:
            - data:/data/db
        image: mongo
    backend:  
        ports:
            - 80:80
        volumes:
            - logs:/logs
            - node_modules:/node_modules
        image: dmehandzhiysky124/exam-task-1-be
    frontend:
        ports:
            - 3000:3000
        volumes:
            - .\frontend\src:/src
        image: dmehandzhiysky124/exam-task-1-fe
networks:
    examnetwork: 
volumes:
    data:
    logs:
    node_modules: